spring:
  mongodb:
    host: 45.82.15.217
  data:
    mongodb:
      host: 45.82.15.217
      port: 27017
      database: default_db
      username: gen_user
      password: verystrongpassword
      authentication-database: admin

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw08booksapp.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local