DROP TABLE IF EXISTS author CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS book CASCADE;

CREATE TABLE author(
    id BIGINT AUTO_INCREMENT,
    name CHARACTER VARYING(255),
    CONSTRAINT author_pk PRIMARY KEY (id)
);


CREATE TABLE genre(
    id BIGINT AUTO_INCREMENT,
    title CHARACTER VARYING(50),
    CONSTRAINT genre_pk PRIMARY KEY (id)
);


CREATE TABLE book(
    id BIGINT AUTO_INCREMENT,
    author_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    title CHARACTER VARYING(50),
    CONSTRAINT book_pk PRIMARY KEY (id)
);

ALTER TABLE book ADD CONSTRAINT book_fk_01 FOREIGN KEY (author_id) REFERENCES author (id);
ALTER TABLE book ADD CONSTRAINT book_fk_02 FOREIGN KEY (genre_id)  REFERENCES genre  (id);