INSERT INTO author(id, name) VALUES (1, 'test');
ALTER TABLE AUTHOR ALTER COLUMN ID RESTART WITH 2;

INSERT INTO genre (id, name) VALUES (1, 'Roman');
ALTER TABLE GENRE ALTER COLUMN ID RESTART WITH 2;

INSERT INTO book(id, author_id, genre_id, title) VALUES (1, 1, 1, 'MasterTest');
ALTER TABLE BOOK ALTER COLUMN ID RESTART WITH 2;

INSERT INTO note(id, book_id, note) VALUES (1, 1,  'Note-01.1 - Master');
ALTER TABLE NOTE ALTER COLUMN ID RESTART WITH 2;