spring:
  mongodb:
    host: 188.225.36.19
  data:
    mongodb:
      host: 188.225.36.19
      port: 27017
      database: default_db
      username: gen_user
      password: tlu|AEj5OpxX
      authentication-database: admin